# Generated by Django 4.0.2 on 2022-02-15 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='subCategories',
        ),
        migrations.AddField(
            model_name='trainer',
            name='password',
            field=models.CharField(default='pass', max_length=20),
        ),
    ]
