# Generated by Django 3.1.14 on 2022-02-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='addres',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='trainer',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainer',
            name='home',
            field=models.TextField(db_column='home', default='', max_length=255, verbose_name='home'),
        ),
    ]
