# Generated by Django 3.1.14 on 2022-02-20 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220220_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutplan',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='api.trainer'),
        ),
        migrations.AlterField(
            model_name='yogaplan',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='api.trainer'),
        ),
    ]
