# Generated by Django 4.0.1 on 2022-02-14 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_workoutplan_numberofeexercises_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutplan',
            name='totalTimeOfExercises',
        ),
        migrations.RemoveField(
            model_name='yogaplan',
            name='numberOfExercises',
        ),
        migrations.RemoveField(
            model_name='yogaplan',
            name='totalDuration',
        ),
    ]
