# Generated by Django 4.0.2 on 2022-02-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delete_category_delete_subcategories_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('password', models.CharField(default='pass', max_length=20)),
                ('is_staff', models.BooleanField(default=False)),
            ],
        ),
    ]
