# Generated by Django 3.1.14 on 2022-02-19 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220219_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weighttracker',
            name='currentWeight',
        ),
    ]
