# Generated by Django 3.1.14 on 2022-02-19 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_weighttracker_currentweight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='currentWeight',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
