# Generated by Django 4.0.1 on 2022-02-14 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_workoutplan_totaltimeofexercises_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutplan',
            name='numberOfEexercises',
        ),
    ]
