# Generated by Django 4.0.2 on 2022-02-19 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='weightTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentWeight', models.CharField(max_length=5, null=True)),
                ('traineeID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.trainee')),
            ],
        ),
    ]
