# Generated by Django 3.1.14 on 2022-02-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220218_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutplan',
            name='exercise',
            field=models.ManyToManyField(blank=True, to='api.WorkoutExcercise'),
        ),
    ]
