# Generated by Django 3.1.14 on 2022-02-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220219_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weighttracker',
            name='traineeID',
        ),
        migrations.AddField(
            model_name='weighttracker',
            name='traineeID',
            field=models.ManyToManyField(blank=True, null=True, to='api.Trainee'),
        ),
    ]
