# Generated by Django 4.0.1 on 2022-02-15 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_workoutplan_numberofeexercises'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workoutplan',
            name='catogery',
        ),
    ]
