# Generated by Django 3.1.14 on 2022-02-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20220218_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='description',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
