# Generated by Django 4.0.2 on 2022-02-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_workoutplan_catogery'),
    ]

    operations = [
        migrations.AddField(
            model_name='yogaplan',
            name='description',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
