# Generated by Django 3.1.14 on 2022-02-18 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_workoutplan_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutplan',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='workoutplan',
            old_name='updated_at',
            new_name='updatedAt',
        ),
    ]
