# Generated by Django 3.1.14 on 2022-02-19 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220219_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weighttracker',
            name='traineeID',
        ),
        migrations.AddField(
            model_name='weighttracker',
            name='traineeID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.trainee'),
        ),
    ]
