# Generated by Django 3.1.14 on 2022-02-18 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220218_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='workoutPlan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.workoutplan'),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='yogaPlan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.yogaplan'),
        ),
    ]
