# Generated by Django 3.1.14 on 2022-02-18 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220218_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainee',
            name='workoutPlan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.workoutplan'),
        ),
        migrations.AlterField(
            model_name='trainee',
            name='yogaPlan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.yogaplan'),
        ),
    ]
