# Generated by Django 3.1.14 on 2022-02-18 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20220218_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainer',
            old_name='home',
            new_name='address',
        ),
    ]
