# Generated by Django 3.1.14 on 2022-02-19 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20220219_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weighttracker',
            name='traineeID',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.trainee'),
        ),
    ]
