# Generated by Django 3.1.14 on 2022-02-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220218_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='address',
            field=models.TextField(),
        ),
    ]
