# Generated by Django 3.1.14 on 2022-02-18 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20220218_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainee',
            name='initialWeight',
        ),
    ]
