# Generated by Django 3.1.14 on 2022-02-19 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_trainee_initialweight'),
    ]

    operations = [
        migrations.CreateModel(
            name='weightTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currentWeight', models.CharField(max_length=5, null=True)),
                ('traineeID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.trainee')),
            ],
        ),
    ]
