# Generated by Django 3.1.14 on 2022-02-19 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_weighttracker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workoutplan',
            old_name='createdAt',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='workoutplan',
            old_name='updatedAt',
            new_name='updated_at',
        ),
    ]
